### ISSUE TITLE
nk_combo not sizing lists correctly

### ISSUE THREAD

**Issue by ewmailing** [vurtun/nuklear#224]
I'm having problems with nk_combo. The lists in the combo box are not sized correctly. This usually results in the list being too short for the box and weird rendering problems happen at the bottom of the box. Sometimes there seems to be garbage, sometimes it just stops short, sometimes the backing layer stops too short and you can see through the box. \

Also, sometimes this causes the last item in the list to be unselectable.

Also, the scrollbar appears, but it really shouldn't because it only scrolls a few pixels. If things were sized correctly, there wouldn't need to be a scrollbar. Scrolling all the way down doesn't help the unselectable problem.

The first picture shows a stop-short.
![screen shot 2016-08-28 at 7 49 17 pm](https://cloud.githubusercontent.com/assets/343240/18039568/2cf26e96-6d59-11e6-95e6-6e02d3e8394d.png)

The second picture shows part of the missing backing.
![screen shot 2016-08-28 at 7 47 58 pm](https://cloud.githubusercontent.com/assets/343240/18039587/5829a868-6d59-11e6-9ac4-93be8f0620c0.png)
 

A related question: is there a way to control the size of the list box? As you can see in the second picture, it is getting really long.

**Comment by vurtun** [comment]
Thanks for the issue. Like you said I had a drawing bug which is now hopefully fixed with commit: 24f7096accfb472e71851c5b38aaae145f839de4 and added scrolling to combo boxes as well as all general non-blocking and blocking popups windows.
About the size of the combo box, you can define the height of the combo box by parameter (at least for the `nk_combo_begin_xxx` calls and I added an additional height parameter to all the retain mode combo boxes in commit: cf272fa2653ffaa505b1da74a7046e64c4c4eeb1.

**Comment by ewmailing** [comment]
I just tested it. It is a little better, but I'm still having problems selecting the very last item in the list. Also, I think the sizing computation is still a little off.

For example, for a 2 item list that I want to show completely (no scrollbar), I expected the max height to be (ROW_HEIGHT+maybe_padding)*2. My ROW_HEIGHT is currently 24. Turns out that the padding needed to be 16 just to get the box big enough to make the scrollbar disappear. (16 seems pretty high.) And still, the selection wasn't working. If I multiply by 4 instead of 2, I can then select the  item. However, the hover-over selection seems a little too high and not vertically centered.

![screen shot 2016-08-29 at 1 54 25 pm](https://cloud.githubusercontent.com/assets/343240/18067389/6e2ef6fc-6df1-11e6-87a3-360e68d378a7.png)

For lists that need to scroll, I can't select the last element.

**Comment by vurtun** [comment]
OK I just got sick of internal complexity and cleaned up some stuff and hopefully finally got combo boxes under control (82e35927b453693662b37769db1198d802db99ae). There is still some small amount of padding but only at the top and bottom which can probably be removed by playing around with either `style->window.spacing` or `style->window,footer_padding`. I will look into that soonish.

**Comment by ewmailing** [comment]
Thank you. The selection problem seems to be fixed. 

However, I noticed some new cracks/glitches in the combo boxes.  (I'm still using +16 for my "maybe_padding" for the time being.)
Here are some pictures.

![screen shot 2016-08-30 at 5 44 47 pm](https://cloud.githubusercontent.com/assets/343240/18112129/29d500e8-6eda-11e6-832e-f9e457722f1a.png)
![screen shot 2016-08-30 at 5 44 14 pm](https://cloud.githubusercontent.com/assets/343240/18112132/349f3368-6eda-11e6-9a7a-784f59cfb8c1.png)
![screen shot 2016-08-30 at 5 48 19 pm](https://cloud.githubusercontent.com/assets/343240/18112134/3db35ccc-6eda-11e6-8adc-f5165ba05bc7.png)

**Comment by vurtun** [comment]
A new commit: fc832cef071ccc0ebc97ad10ac82fd7e71d4d4f3 another try to finally get everything back to running smoothly. I basically hacked in a solution because I have no idea at the moment from where these gaps come from. Especially since it does work under `xlib` but not vertex buffer based renderer. Will see in the future if it causes anymore problem.

**Comment by ewmailing** [comment]
Things are overall improved. However, there are still some issues. I'll describe them in case they may reveal something to you about what's going on.

First, I'm seeing a sizing problem with one of my combo boxes, where no matter what I do, I can't seem to make the height values big enough to make the scrollbar go away. It always keeps the scrollbar with just a few pixels to scroll. (Picture attached.)


![screen shot 2016-09-03 at 11 25 29 am](https://cloud.githubusercontent.com/assets/343240/18227775/9bcc71d8-71e4-11e6-804d-fb2a0c94aabd.png)


What's strange is I don't have a problem making this smaller, 2-item combo box remove the scrollbar.

![screen shot 2016-09-03 at 2 46 21 pm](https://cloud.githubusercontent.com/assets/343240/18227818/f2cab368-71e5-11e6-926f-e8a3aa531d7f.png)




Second, I'm still seeing a crack in some cases. Here is another picture. You can see there is a vertical crack a little left of the scrollbar (white background showing through). Also, near the top of the combo box, you can see a horizontal crack where the top line of text should be clipped.

![screen shot 2016-09-03 at 10 57 14 am](https://cloud.githubusercontent.com/assets/343240/18227786/d9d17cc6-71e4-11e6-80e7-1fd5471f7855.png)

The background color combo box seen in prior attachments still has the vertical crack too.


But I have another color combo box that doesn't have the crack. One pattern I'm starting to see (may or may not be real) is that my boxes that use 2-column layout (using ratio: .25, .75 or something like that), seem to have the problems, while the 1-column layout does not. (This is true of the 2-item combo box too.)


![screen shot 2016-09-03 at 2 53 28 pm](https://cloud.githubusercontent.com/assets/343240/18227825/5ec36e7a-71e6-11e6-8e01-2c68b7c55805.png)

Thanks

**Comment by vurtun** [comment]
Really quick question. Do you use `nk_combobox` or `nk_combo_begin_xxx` and if both in which cases do you get the scrollbar and gap bug?

**Comment by ewmailing** [comment]
Good question. It looks like I'm using nk_combo() for all the regular combo boxes. And I am using nk_combo_begin_color() for all the color combo boxes.

There doesn't seem to be a connection between the gap bug and this. I have some combo boxes that are buggy and some that are fine. And I have some color combos that are buggy and some that are fine.

The only pattern I'm noticing right now (there might be others) is the 2-column vs. 1-column.

**Comment by vurtun** [comment]
Small update the scrollbar issue is because of my wrong height calculation inside the array based comb box functions. So that issue is now fixed. Next up is the gap issue.
I also tried the 2-column combo box and it rendered fine for me just like the 1-column. I have to dig deeper here I guess.

**Comment by vurtun** [comment]
Could you try out the new commit and see if there are any updates on the gaps? I just don't seem to be able to reproduce the bug.

**Comment by ewmailing** [comment]
Thank you. The combo height calculation seems to be much better now.

I still see the gaps. (I also started noticing issues in my nk_menu_begin_symbol box. They've probably always been there but I didn't notice.)
However, I noticed that resizing my viewport (to support window resizing) can make the gaps come and go. It seems that by bad luck, the default launch size on my main systems seems to show the pixel gap. On other systems that have a different desktop resolution, I don't see this until I play with the resizing. 


I made some builds you can run for yourself to see the effect. Hopefully you can hit a particular size that shows the gap. 
http://playcontrol.net/tempdownload/BlurrrBinaries/FairyDance/SparkleSparkle_OSX_Signed.zip
http://playcontrol.net/tempdownload/BlurrrBinaries/FairyDance/SparkleSparkle_Linux.tar.gz
http://playcontrol.net/tempdownload/BlurrrBinaries/FairyDance/SparkleSparkle_WinSigned_GPU_Default.zip

And again, it only seems to happen for the 2-column combo boxes. The bigger single column boxes I never see a gap.

If it would be useful to you, I can also make the source to this program available to you. (And I have an easy way so you can build it. I sympathize with why single header files are done. But I've been attacking the opposite end of the problem when you have dependencies that don't let you do that.)

Thanks

**Comment by vurtun** [comment]
I tried your program and I get the gap in every combo box except the double color combo boxes and it always one pixel. Like you said it is not showing up  every time but only if the correct size is hit. Menu also has it which is to be expect since it shares the same code.

While nice to actually try it out myself I still am not able to reproduce and debug the problem. So what would be great is if like you said provide me with some source (just send by email) or create just extend the default SDL demo enough to reproduce the problem.

One additional thing you could try is to play around with `nk_panel_end` at line 16645 and check if it is a floating point error. For example what you could try is:

```c
        /* fill top empty space */
        empty_space.x = window->bounds.x;
        empty_space.y = layout->bounds.y;
        empty_space.h = panel_padding.y;
        empty_space.w = window->bounds.w;
        nk_fill_rect(out, empty_space, 0, style->window.background);

        /* fill left empty space */
        empty_space.x = window->bounds.x;
        empty_space.y = layout->bounds.y;
        empty_space.w = panel_padding.x + layout->border + 0.5f;
        empty_space.h = layout->bounds.h;
        nk_fill_rect(out, empty_space, 0, style->window.background);

        /* fill right empty space */
        empty_space.x = layout->bounds.x + layout->bounds.w - layout->border - 0.5f;
        empty_space.y = layout->bounds.y;
        empty_space.w = panel_padding.x + 2*layout->border + 1.0f;
        empty_space.h = layout->bounds.h;
        if (layout->offset->y == 0 && !(layout->flags & NK_WINDOW_NO_SCROLLBAR))
            empty_space.w += scrollbar_size.x;
        nk_fill_rect(out, empty_space, 0, style->window.background);

        /* fill bottom empty space */
        if (layout->offset->x != 0 && !(layout->flags & NK_WINDOW_NO_SCROLLBAR)) {
            empty_space.x = window->bounds.x;
            empty_space.y = layout->bounds.y + layout->bounds.h;
            empty_space.w = window->bounds.w;
            empty_space.h = scrollbar_size.y;
            nk_fill_rect(out, empty_space, 0, style->window.background);
        }
```
I just add `0.5f` but you could play around with it to test some things as well.

**Comment by ewmailing** [comment]
I entered in the two 0.5f's and the 1.0f you showed. It actually seems to have fixed the right-side pixel crack in my combo boxes. So, good call.

The remaining one is the left side one I see in my Menu box. I haven't figured out what values affect that glitch. (Picture attached.)

![screen shot 2016-09-07 at 11 36 47 pm](https://cloud.githubusercontent.com/assets/343240/18339521/d14314d4-7554-11e6-8cbc-d48ceb913380.png)
